### ISSUE TITLE
Null values on integer or float type fields are getting cast to 0

### ISSUE THREAD

**Issue by jenskdsgn** [NestAway/salesforce-orm#23]
I don't think that is a good and expected behaviour. E.g. you don't know if the field value is actually Null or set to 0 on purpose.

**Comment by jenskdsgn** [comment]
PR: https://github.com/NestAway/salesforce-orm/pull/24

**Comment by jenskdsgn** [comment]
@vishalvijay  @shivanshgaur what do you guys think about the issue?

**Comment by shivanshgaur** [comment]
Merged PR: #24

**Comment by jenskdsgn** [comment]
@shivanshgaur can you make a release inlcuding this fix?

**Comment by vishalvijay** [comment]
@jenskdsgn Version 1.3.1 released with this change.
